apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    network-plugin: aci-containers
  name: ul-tester
spec:
  selector:
    matchLabels:
      name: ul-tester
  template:
    metadata:
      labels:
        name: ul-tester
    spec:
      containers:
      - env:
        - name: http_proxy
          value: ""
        - name: https_proxy
          value: ""
        name: ul-tester
        image: contiv/util-busybox
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
          - "exec tail -f /dev/null"
      hostNetwork: true
